export const BUTTON_COLOR_ADD_REQUEST = 'BUTTON_COLOR_ADD_REQUEST';
export const BUTTON_COLOR_ADD_REQUEST_SUCCESS = 'BUTTON_COLOR_ADD_REQUEST_SUCCESS';
export const BUTTON_COLOR_ADD_REQUEST_FAILURE = 'BUTTON_COLOR_ADD_REQUEST_FAILURE';

export const BUTTON_COLOR_CLEAN_REQUEST = 'BUTTON_COLOR_CLEAN_REQUEST';